installation_proxy: add `install_from_bytes()`
doronz88/pymobiledevice3 pull request #1266
Opened 2024-10-29 20:41 UTC by Abdullah-Albanna

ability to install .ipa/.ipcc using bytes objects

### why?

it's way nicer to directly install a package without dealing with paths.

someone could do something like so

```Python
import requests
from pymobiledevice3.lockdown import create_using_usbmux
from pymobiledevice3.services.installation_proxy import InstallationProxyService

file = requests.get(
    "https://raw.githubusercontent.com/Abdullah-Albanna/YemenIPCC/refs/heads/master/iPhone7Plus/iOS 15.8.2/Using Default Bundle/iPhone7Plus_iOS_15.8.2_CellularSouthLTE.ipcc",
)

lockdown = create_using_usbmux()

InstallationProxyService(lockdown).install(file.content)

```

without the need to save it to a file and then installing it and then deleting it !
too much work

this is also valid 

```Python

from pathlib import Path

file = Path("file.ipa").read_bytes()

lockdown = create_using_usbmux()

InstallationProxyService(lockdown).install(file)

```

2024-10-29 22:10 UTC, doronz88 commented
I much rather it be explicitly done than implicit. I'm okay with the `install_from_bytes()`, but it should a different API instead of modifying the current

2024-10-30 17:14 UTC, Abdullah-Albanna commented
that makes sense, should be good now

2024-10-30 18:08 UTC, doronz88 requested changes

2024-10-30 18:08 UTC, doronz88 commented on pymobiledevice3/cli/apps.py
> +    InstallationProxyService(lockdown=service_provider).install(package)
there is no actual reason for this diff

2024-10-30 18:08 UTC, doronz88 commented on pymobiledevice3/services/installation_proxy.py
> +    def install(self, package: str, options: Optional[dict] = None, handler: Callable = None, *args) -> None:
restore old name

2024-10-30 18:08 UTC, doronz88 commented on pymobiledevice3/services/installation_proxy.py
> +def classify_zip_file(zip_bytes: bytes) -> Literal['ipa', 'ipcc']:
use python's Enum instead

2024-10-30 18:08 UTC, doronz88 commented on pymobiledevice3/services/installation_proxy.py
> +                raise AppInstallError('package does not have a payload')
```suggestion
                raise InvalidArgumentError('package does not have a payload')
```

2024-10-30 18:08 UTC, doronz88 commented on pymobiledevice3/services/installation_proxy.py
> +        raise AppInstallError('invalid bytes package')
```suggestion
        raise InvalidArgumentError('invalid bytes package')
```

2024-10-30 18:08 UTC, doronz88 commented on pymobiledevice3/services/installation_proxy.py
> +
remove this diff

2024-10-30 18:08 UTC, doronz88 commented on pymobiledevice3/services/installation_proxy.py
> +    def upload_ipcc_as_folder(self, file: Union[Path, bytes], afc_client: AfcService) -> None:
restore this function behavior to the old one. the bytes objects can already be convered to file in `install_from_bytes()`

2024-11-17 08:36 UTC, doronz88 commented
Just making sure you saw I left some comments still

2024-11-25 13:43 UTC, Abdullah-Albanna commented
sorry, I don't get what you mean

can you tell me what to edit please, I understood some of it, but others are kind of confusing

2024-11-25 18:18 UTC, doronz88 commented
There are still unresolved issues. See the existing comments

2024-11-25 18:21 UTC, Abdullah-Albanna commented
Yeah but could you take a look at my replies please 

The unresolved ones are what confuses me, I have already put a reply to them

2024-11-25 18:22 UTC, doronz88 commented
![image](https://github.com/user-attachments/assets/8ee2e654-7993-4783-a80b-2a8d96821dfc)
I don't see any reply to any comment

2024-11-25 18:29 UTC, abdullah-albanna commented on pymobiledevice3/cli/apps.py
> +    InstallationProxyService(lockdown=service_provider).install(package)
what's the point of .install()?

2024-11-25 18:29 UTC, abdullah-albanna commented on pymobiledevice3/services/installation_proxy.py
> +                raise AppInstallError('package does not have a payload')
where is that exception?

2024-11-25 18:29 UTC, abdullah-albanna commented on pymobiledevice3/services/installation_proxy.py
> +
I don't understand, remove what?

2024-11-25 18:29 UTC, abdullah-albanna commented on pymobiledevice3/services/installation_proxy.py
> +    def upload_ipcc_as_folder(self, file: Union[Path, bytes], afc_client: AfcService) -> None:
what do you mean?,  .ipcc  must be uploaded as a folder for both of the bytes and the path

correct me if that's not what you mean

2024-11-25 18:30 UTC, Abdullah-Albanna commented
my bad, I did not commit them

2024-11-25 21:11 UTC, doronz88 requested changes

2024-11-25 21:11 UTC, doronz88 commented on pymobiledevice3/services/installation_proxy.py
> +
this extra line what was added in the PR

2024-11-25 21:11 UTC, doronz88 commented on pymobiledevice3/services/installation_proxy.py
> +    def upload_ipcc_as_folder(self, file: Union[Path, bytes], afc_client: AfcService) -> None:
i don't want an api function acting differently depending in its supplied arguments. if it performs another logic it should be in its own api. the expected `file` argument can remain `Path`

2024-11-25 22:06 UTC, abdullah-albanna commented
I like how it gets crazy over an unused import

2024-11-26 06:15 UTC, doronz88 approved these changes

2024-11-26 06:21 UTC, merged

2024-11-26 06:21 UTC, doronz88 commented
Thanks for your contribution!