Do not interrupt the copy if an error occurs
doronz88/pymobiledevice3 pull request #1281
Opened 2024-11-15 20:06 UTC by 0xepsil0n

2024-11-17 06:30 UTC, doronz88 requested changes
Ignoring all possible errors should not be considered a good practice. Let's instead use an optional `ignore_errors: bool = False` to the `pull()` method.

2024-11-17 06:30 UTC, doronz88 requested changes

2024-11-17 06:30 UTC, doronz88 commented on pymobiledevice3/services/afc.py
> +                    print("Error", e, "occured during the copy of", src_filename)
use logger instead

2024-11-17 20:04 UTC, 0xepsil0n commented on pymobiledevice3/services/afc.py
> +                    print("Error", e, "occured during the copy of", src_filename)
Changed!

2024-11-17 20:04 UTC, 0xepsil0n commented
> Ignoring all possible errors should not be considered a good practice. Let's instead use an optional `ignore_errors: bool = False` to the `pull()` method.

Done!

2024-11-17 20:59 UTC, 0xepsil0n commented
Is there any way I can run those tests before pushing them?

2024-11-17 23:52 UTC, doronz88 commented
@0xepsil0n yeah you can install the pre-commit hook before committing.
```shell
python3 -m pip install pre-commit
pre-commit install
```

2024-11-18 20:35 UTC, doronz88 requested changes

2024-11-18 20:35 UTC, doronz88 commented on pymobiledevice3/services/afc.py
> +                        exit(1)
this will exit the entire python process which is not an expected behavior from a python function. also, i much rather this flag will be documented in the function docstring instead of printed as an "howto".
finally, simply trigger `raise` here.

2024-11-18 20:35 UTC, doronz88 commented on pymobiledevice3/services/afc.py
> +                    if (ignore_errors):
```suggestion
                    if not ignore_errors:
                        raise
                    self.logger.warning("(Ignoring) Error:", afc_exception, "occured during the copy of", src_filename)
```

2024-11-18 20:36 UTC, 0xepsil0n commented on pymobiledevice3/services/afc.py
> +                        exit(1)
ok!

2024-11-18 21:06 UTC, doronz88 approved these changes

2024-11-18 21:07 UTC, merged

2024-11-18 21:07 UTC, doronz88 commented
Thanks for the contribution! :)