add feature XCUITest
doronz88/pymobiledevice3 pull request #780
Opened 2024-01-12 14:41 UTC by codeskyblue

2024-01-16 01:49 UTC, codeskyblue commented
Are there any codes that need me to update?

2024-01-16 06:14 UTC, doronz88 requested changes
just the apps lookup issue

2024-01-16 06:14 UTC, doronz88 commented on pymobiledevice3/cli/developer.py
> +    # TODO: install_service.lookup is not working for RSD，use browse instead
rebase on master. i added a `bundle_identifiers` keyword for that which also should be much faster

2024-01-16 12:49 UTC, codeskyblue commented
done @doronz88

2024-01-16 15:18 UTC, doronz88 requested changes
please rebase the commits to contain:

- process_control: add `extra_options` to `launch()`
- developer: add xcuitest support

if you're having trouble with `git rebase`, i can do it myself, but then the commit author will change to me and I want you to have the credit on it :)

2024-01-21 06:03 UTC, doronz88 commented
@codeskyblue I meant for the two commits to be separate. One for modifying the `process_control` and the other for the rest - Splitting the two commits into 2 logical units

2024-01-22 06:31 UTC, doronz88 approved these changes

2024-01-22 06:34 UTC, merged

2024-01-22 06:35 UTC, doronz88 commented
merged! thanks for you contribution :)

2024-02-16 22:33 UTC, krishtoautomate commented
how to test this?

I tried with : 
`python3 -m pymobiledevice3 developer dvt xcuitest RDSRunner.xctrunner --rsd fd90:609e:8a9f::1 54232`

but not able to access http://<ip-of-the-device>:8100

2024-02-18 02:02 UTC, codeskyblue commented
@krishtoautomate yes, it is not working for iOS17 now.

2024-03-20 11:18 UTC, corrrso commented
Hello @codeskyblue , Are there any plans to make this work with iOS17?

2024-03-21 03:48 UTC, codeskyblue commented
> Hello @codeskyblue , Are there any plans to make this work with iOS17?

No plans