temp windows tunnel fix
doronz88/pymobiledevice3 pull request #797
Opened 2024-01-22 14:06 UTC by DsoTsin

2024-01-22 15:27 UTC, doronz88 requested changes
Thanks for the contribution! please just fix the mentioned issues

2024-01-22 15:27 UTC, doronz88 commented on pymobiledevice3/remote/bonjour.py
> +    if sys.platform == 'win32':
please add a comment explaining why this is necessary

2024-01-22 15:27 UTC, doronz88 commented on pymobiledevice3/remote/core_device_tunnel_service.py
> +                    #assert packet.startswith(LOOKBACK_HEADER)
remove the commented out code

2024-01-23 03:41 UTC, DsoTsin commented on pymobiledevice3/remote/bonjour.py
> +    if sys.platform == 'win32':
On windows, the default BONJOUR_TIMEOUT 1 second is not enough to get the address, this line is a hack.
``` python
    for bonjour_query in bonjour_queries:
        bonjour_query.service_browser.join()
        addresses += bonjour_query.listener.addresses
        #bonjour_query.service_browser.cancel()
        bonjour_query.zc.close()
```

2024-01-23 09:42 UTC, doronz88 requested changes

2024-01-23 09:42 UTC, doronz88 commented on pymobiledevice3/remote/core_device_tunnel_service.py
> +    from pywintun_pmd3 import TunTapDevice
this package should both be added to project's requirements and uploaded to pypi

2024-01-25 14:12 UTC, doronz88 approved these changes

2024-01-30 06:02 UTC, merged